# Generated by Django 3.2.20 on 2023-07-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=3000)),
                ('subject', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
